---
title: "Youngdeok Hwang"
fontsize: 15pt
---

<style type="text/css">

body, td {
   font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

youngdeok.hwang_at_baruch_cuny_dot_edu\
Paul H. Chook Department of Information Systems and Statistics\
Baruch College, City University of New York\
One Bernard Baruch Way, New York, NY 10010\
Office: 11-225\
+1 646-312-3411\

<!-- I am an assistant professor at the [Department of Statistics](http://shb.skku.edu/stat/), [Sungkyunkwan University (SKKU)](http://www.skku.edu/eng_home/index.jsp). Before joining SKKU, I worked as a statistician at [IBM TJ Watson Research Center](http://www.research.ibm.com/labs/watson/index.shtml). I'm interested in developing new statistical methodologies for solving problems in industry and engineering -- in the area of design and analysis of computer experiments, remote-sensing technology, wireless sensor networks and IoT.  -->

### Employment

[Paul H. Chook Department of Information Systems and Statistics](https://zicklin.baruch.cuny.edu/Department/cis-faculty/), [Baruch College](https://www.baruch.cuny.edu), [CUNY](https://www2.cuny.edu), New York, NY

- Assistant Professor. Aug 2019 - Present

[Department of Statistics, Sungkyunkwan University (SKKU)](http://www.skku.edu/eng_home/index.jsp), Seoul, Korea

- Assistant Professor. Aug 2017 - Aug 2019

[IBM TJ Watson Research Center](http://www.research.ibm.com/labs/watson/index.shtml), [Yorktown Heights](https://goo.gl/maps/XJVGy1Rk8U82), [NY](http://www.ny.gov)

- Research Staff Member.  Mar 2014 - Aug 2017 
- Postdoctoral Researcher. Sep 2012  - Feb 2014

### Education

[University of Wisconsin - Madison](http://www.wisc.edu), [Madison](http://www.cityofmadison.com ), [WI](http://www.wisconsin.gov/)  

- Ph.D., [Statistics](http://www.stat.wisc.edu), 2012.
- M.S.,  [Statistics](http://www.stat.wisc.edu), 2010.

### Research Interests

* Analytics in Technology, Business and Service
* Inverse Problems and Uncertainty Quantification
* Spatio-Temporal Statistics
* Design of Experiments



### Honors

* [Statistics in Physical Engineering Sciences Award](http://www.amstat.org/ASA/Your-Career/Awards/Statistics-in-Physical-Engineering-Sciences-Award.aspx), [American Statistical Society](http://www.amstat.org), 2018.
* Career Development Award, [Korean International Statistical Society](https://statkiss.org), 2016.
* [Army Commendation Medal](https://www.govinfo.gov/content/pkg/CFR-2008-title32-vol3/xml/CFR-2008-title32-vol3-sec578-20.xml), United States Department of the Army, 2004.


### Publication

#### Statistics Journals
1. Hwang, Y., Kim, H. J., Chang, W., Hong, C., and MacEachern, S. N. (2021+).
Bayesian Model Calibration and Sensitivity Analysis for Oscillating Biological Experiments. Submitted. prepreint on [arxiv:2110.10604](https://arxiv.org/abs/2110.10604).
1. Hwang, Y., Lee, E., Cho, D., Zhang, Q. (2021+). A Spline-based  Modeling Approach for Time-Indexed Multilevel Data. Submitted.
1. Sung, C. -L., Haaland, B. Hwang, Y.  and  Lu, S. (2021+) A clustered Gaussian process model for computer experiments. *Statistica Sinica*, forthcoming. prepreint on [arXiv:1911.04602](https://arxiv.org/abs/1911.04602).
1. Yang, S., Kim, J. and Hwang, Y. (2021) [Integration of survey data and big observational data for finite population inference using mass imputation](https://www150.statcan.gc.ca/n1/pub/12-001-x/2021001/article/00004-eng.htm). *Survey Methodology*. **47**, 29-58. 
1. Zhang, Q. and  Hwang, Y. (2020). [Sequential Model-based Optimization for Continuous Inputs with Finite Decision Space](https://doi.org/10.1080/00401706.2019.1665589). *Technometrics*. **62**, 486-498.
1. Xu, X., Hwang, Y., Kim, T., Wang, F., Wang, X., Chien, P. (2020). [Level-expansion: A Statistical Sequential Design Methodology with Application to Nanomaterial Synthesis](https://www.tandfonline.com/doi/full/10.1080/00224065.2019.1571335). *Journal of Quality Technology*. **52**, 97-107.
1. Sun, F., Gramacy, R. B., Haaland, B., Lu, S. and Hwang, Y. (2019).
[Synthesizing Simulation and Field Data of Solar Irradiance](https://onlinelibrary.wiley.com/doi/full/10.1002/sam.11414). *Statistical Analysis and Data Mining*, **12**, 311-324. preprint on [arXiv:1806.05131](https://arxiv.org/abs/1806.05131).
1. Hwang, Y., Kim, H., Chang, W., Yeo, K. and Kim, Y. (2019). [Bayesian Pollution Source Identification via an Inverse Physics Model](https://www.sciencedirect.com/science/article/pii/S0167947318302822).  *Computational Statistics and Data Analysis*, **134**, 76-92.
1. Hwang, Y., Lu, S. and Kim, J. (2018). [Bottom-up Estimation and Top-down Prediction: Solar Energy Prediction Combining Information from Multiple Sources](http://dx.doi.org/10.1214/18-AOAS1145). *Annals of Applied Statistics*, **12**, 2096-2120. 
1. Hwang, Y., Barut, E., and Yeo, K. (2018). [Statistical-physical Estimation of Pollution Emission](http://www3.stat.sinica.edu.tw/statistica/J28N2/J28N217/J28N217.html). *Statistica Sinica*, **28**, 921-940.
1. Hwang, Y., Wright, S., and Hanlon, B. (2017). [Estimation and Testing Problems in Auditory Neuroscience via Clustering.](http://onlinelibrary.wiley.com/doi/10.1111/biom.12652/full) *Biometrics*,
**73**, 1010–1017. 
1. Hwang, Y., He, X. and Qian, P. Z. G. (2016). [Sliced Orthogonal Array Based Latin Hypercube Designs.](http://www.tandfonline.com/doi/abs/10.1080/00401706.2014.993092) *Technometrics*, **58**, 50–61.
1. Liu, X., Yeo, K., Hwang, Y., Singh, J. and Kalagnanam, J. (2016). [A Statistical Modeling Approach for Air Quality Data Based on Physical Dispersion Processes and Its Application to Ozone Modeling.](http://projecteuclid.org/euclid.aoas/1469199892) *Annals of Applied Statistics*, **10**, 756–785.
1. Jiang, H., Schörgendorfer, A., Hwang, Y. and Amemiya, Y. (2015). [A Practical Approach to Spatio-Temporal Analysis.](http://www.jstor.org/stable/24311021) *Statistica Sinica*, **25**, 369-384.
1. Qian, P. Z. G., Ai, M., Hwang, Y., and Su, H. (2014). [Asymmetric Nested Lattice Samples.](http://www.tandfonline.com/doi/abs/10.1080/00401706.2013.800002) *Technometrics*, **56**, 46–54.


#### Collaborative 
1. Lim, S., Choo, E. Choi, I. Hwang, Y. Lee, K. Lee, S. Hwang, B.,Kim, C., Park, M., Lee, J., Park, C., Kim, H., Yoo, K., Jeon, D., Youn, Ho. , Chung, W., Kim, M., Jeong, M. Yim, H., Ahn, Y., and Chang, K. (2021+). Impact of malnutrition on bleeding, mortality, and ischemic events in patients with acute myocardial infarction undergoing percutaneous coronary intervention. Submitted.
1. Tuakli-Wosornu, Y. A., Pandiyan, U., Stratton, C., Hwang, Y., Hajjioui, A., Muñoz-Velalsco, L. P., 
 Fourtassi, M., Cooper, R., Balikuddembe, J. K., Peterson, M., Krassioukov, A., Palomba, A., Tripathi, D. R., Hong, B. (2022). 
 [Perceived Physical and Mental Health and Healthy Eating Habits During the COVID-19 Pandemic in South Korea](https://jkms.org/DOIx.php?id=10.3346/jkms.2022.37.e118). *Journal of Korean Medical Science*. **37**(15), e118.
1. Sim, J., Cho, D., Hwang, Y., and Telang, R. (2022). [Virus Shook the Streaming Star: Estimating the COVID-19 Impact on Music Consumption](https://pubsonline.informs.org/doi/abs/10.1287/mksc.2021.1321).  *Marketing Science.* **41**(1), 19-32. preprint on
[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3649085), [Press release](https://zicklin.baruch.cuny.edu/zicklin_news/music-streaming-declined-during-pandemic-zicklin-professor-finds/)
1. Choi, W., Park, S., Kwon, J., Jang, E, Kim, J, Heo, J, Hwang, Y., Kim, B., Moon, J., Jung, S., Choi, S., Lee, H., Ahn, H., and Hong, J. (2021). [Reverse Actuation of Polyelectrolyte Effect for In Vivo Antifouling](https://pubs.acs.org/doi/full/10.1021/acsnano.0c10431). *ACS Nano*. **15** (4) 6811–6828.
1. Choi, D., Hwang, J., Bang, J., Han, S., Kim, T., Oh, Y., Hwang, Y., Choi, J., and Hong, J. (2021).
[In Vitro Toxicity from a Physical Perspective of Polyethylene Microplastics Based on Statistical Curvature Change Analysis](https://www.sciencedirect.com/science/article/abs/pii/S0048969720357715). *Science of the Total Environment*. **752**, January 2021, 142242.
1. Han, S., Bang, J., Choi, D., Hwang, J., Kim, T., Oh, Y., Hwang, Y., Choi, J., and Hong, J. (2020).
[Surface Pattern Analysis of Microplastics and Impact on Humans](https://pubs.acs.org/doi/abs/10.1021/acsapm.0c00645). *ACS Applied Polymer Materials*. **2.11** 4541-4550.
1. Sung, W., Kim, W., Hwang, Y., Kim, J., Lim, S., Hong, B. (2020) [Body composition of school-aged children with disabilities](https://onlinelibrary.wiley.com/doi/abs/10.1111/ped.14248?casa_token=L8ZPhUKA-sUAAAAA:7c4JbknFhJXkPCC59Zo8xpgrorSJ4LC02Ta-JhQ8HtpiATHn9wd38YBs8WQEBHiqgNqz7sn2ZxcQjw). *Pediatrics International*, **62**(8), 962-969.
1. Choi, D., Bang, J., Kim, T., Oh, Y., Hwang, Y., and Hong, J. (2020).
[In Vitro Chemical and Physical Toxicities of Polystyrene Microfragments in Human-derived Cells](https://doi.org/10.1016/j.jhazmat.2020.123308). *Journal of Hazardous Materials*. **400**, 5 December 2020, 123308.
1. Choi, I., Lim, S., Hwang, Y., Lee, D., Lee, W., Lee, K., Kim, M. and Jeon, D. (2020). [Soluble neprilysin and long-term clinical outcomes in patients with coronary artery disease undergoing percutaneous coronary intervention: a retrospective cohort study](https://bmccardiovascdisord.biomedcentral.com/articles/10.1186/s12872-020-01636-5). *BMC Cardiovascular Disorders*, **20**(1), 1-10.
1. Kim, S., Hwang, Y., Seo, H., Kim, B. (2020).
[Ground Motion Amplification Models for Japan using Machine Learning Techniques](https://doi.org/10.1016/j.soildyn.2020.106095). *Soil Dynamics and Earthquake Engineering*, **132**, 106095.
1. Lee, H. Kim, E., Baek, D., Hwang, Y., Kim, J., Lim, S., Sul, B. and Hong, B. (2019).
[The Role of Regular Physical Therapy on Spasticity in Children with Cerebral Palsy](https://www.e-arm.org/journal/view.php?number=4093). *Annals of Rehabilitation Medicine*, **43**, 289-296.
1. Yeo, K., Hwang, Y., Liu, X. and Kalagnanam, J. (2019). [Development of *hp*-inverse Model by Using Generalized Polynomial Chaos.](https://www.sciencedirect.com/science/article/pii/S0045782518306212?dgcid=author) *Computer Methods in Applied Mechanics and Engineering,* **347**, 1-20.
1. Cho, D. and  Hwang, Y. and Park, J. (2018). [More Buzz, More Vibes: Impact of Social Media on Concert Distribution](https://doi.org/10.1016/j.jebo.2018.09.012). *Journal of Economic Behavior & Organization*, **156**, 103-113.
1. Wright, S., Wallace, E. and Hwang, Y. and Maganti, R. (2016). [Seizure Phenotypes and Sleep–Wake Pattern of Seizures in KCNA1-null Mutant Mice.](http://www.sciencedirect.com/science/article/pii/S1525505015006538) *Epilepsy & Behavior*, **55**, 24–29.
1. Chae, Y. T., Horesh, R., Hwang, Y., Lee, Y. M. (2016). [Artificial Neural Network Model for Forecasting Sub-Hourly Electricity Usage in Commercial Buildings](http://www.sciencedirect.com/science/article/pii/S0378778815304102). *Energy and Buildings*, **111**, 184–194.
1. Wright, S., Hwang, Y., and Oertel, D. (2014). [Synaptic Transmission between End bulbs of Held and Bushy Cells in the Cochlear Nucleus of Mice with a Mutation in Otoferlin.](http://jn.physiology.org/content/112/12/3173) *Journal of Neurophysiology*, **112**, 3173–3188.
1. Hong, B., Ko, Y., Kim, J., Ok, E., Hwang, Y. and Kim, H. (2013). [Sternocleidomastoid Ultrasonography Data for Muscular Torticollis in Infants.](http://onlinelibrary.wiley.com/doi/10.1002/mus.23712/full) *Muscle & Nerve*, **48**, 100- 104.
1. Chung, H., Kong, E., Edwards, J., Weismer, G., Fourakis, M. and Hwang, Y. (2012). [Cross-linguistic Studies of Children’s and Adults’ Vowel Spaces.](http://asa.scitation.org/doi/abs/10.1121/1.3651823) *The Journal of the Acoustical Society of America*. **131**, 442–454.
1. Wang, F., Hwang, Y., Qian, P. Z. G. and Wang, X. (2010). [A Statistics-Guided Approach to Precise Characterization of Nanowire Morphology.](http://pubs.acs.org/doi/abs/10.1021/nn901530e) *ACS Nano*, **4**, 855–862.


<!-- ### Reports -->


<!-- 1. Qian, P., Amemiya, Y.,  Hwang, Y. (2017). A Structural Equation Method for Modeling Multivariate Data from Computer Experiments: with Application to Data Center Thermal Management. Under revision for *Technometrics*. -->

### Teaching

##### At Baruch College
* STA 9719 - Foundations of Statistical Inference 2021S, 2022S
* STA 9708 - Managerial Statistics 2020F, 2021F 
* STA 3154 - Business Statistics II 2020S, 2020F, 2021F, 2022F
* STA 4370 - Introduction to Statistical Engineering 2022F
* STA 9661 - Multivariate Statistics for Business Analytics -- with DataCamp 2019F

##### At SKKU
* Statistical Consulting -- with DataCamp (STA5034) 2019S
* Large Scale Data Management and Visualization -- with DataCamp (STA3034) 2018F
* Introduction to Statistical Computing -- with DataCamp (STA2016) 2018F, 2019S
* Design and Analysis of Experiments (STA5031) 2018S
* Design of Experiments (STA3026) 2018S
* Introduction to Mathematical Statistics (STA2014) 2017F

### Selected Presentations
* Department of Mathematics and Statistics, University of Maryland at Baltimore County (UMBC). Baltimore, MD. 2021.
* Department of Mathematical Sciences, University of Cincinnati, Cincinnati, OH. 2020.
* Department of Statistics, Inha  University, Incheon, Korea. 2019. 
* Department of Statistics, Chung-Ang  University, Seoul, Korea. 2018. 
* Department of Statistics, Seoul National University, Seoul, Korea. 2018. 
* Tutorial on Industrial Statistics, International Conference on Consumer Electronics Asia. Jeju, Korea. 2018.
* The 2nd Pacific Rim Statistical Conference for Production Engineering, Seoul, Korea. 2016. 
* Department of Statistics, Korea University, Seoul, Korea. 2016. 
* Department of Industrial & System Engineering, KAIST, Daejeon, Korea. 2015.
* H. Milton Stewart School of Industrial & Systems Engineering, Georgia Institute of Technology, Atlanta, GA. 2015.
* Department of Industrial and Management Engineering, POSTECH. Pohang, Korea. 2014.

### Research Grants

* NRF-2017R1C1B5075436 (PI, 2017-2019).
* NRF-2018M3A9E8021503 (Co-PI, 2018-2022). 
* KOFAC-2018FBA0007 (Undergraduate Research Program, 2018F).

### Patent

* Multi-model Blending (US20150347922 A1)
* Building Energy Consumption Forecasting Procedure Using Ambient Temperature, Enthalpy, Bias Corrected Weather Forecast and Outlier  Corrected Sensor Data (US20150331023)
* Parameter-dependent model-blending with multi-expert based machine learning and proxy sites (US20170017895 A1)
* Detection Algorithms for Distributed Emission Sources of Abnormal Events (US20170147927)

<!-- ### Consulting -->

<!-- * Statistical Model Building, IBM T. J. Watson Research Center, Aug 2018 - Present. -->


### Membership

* [American Statistical Association](http://www.amstat.org) 
* [Korean International Statistics Society](https://statkiss.org)
* [Korean Statistical Society](http://www.kss.or.kr) 
* [INFORMS](https://www.informs.org) 

### Professional Service

* Associate editor for [Technometrics](https://www.tandfonline.com/journals/utch20) 2022 - 
* Associate editor for [Applied Stochastic Models in Business and Industry](https://onlinelibrary.wiley.com/journal/15264025) 2018 - 2022

Referee for _Technometrics, Statistica Sinica, Computational Statistics & Data Analysis, Journal of Nonparametric Statistics, Statistics and Probability Letters, PLOS ONE, SIAM/ASA Journal on Uncertainty Quantification._

```{r, echo=FALSE}
htmltools::includeHTML("analytics.html")
```

### Miscellaneous

- [Google Scholar profile](https://scholar.google.com/citations?user=pEdCzOQAAAAJ&hl=en)
- [Github](https://github.com/ydhwang)
- [Twitter](https://twitter.com/youngdeokhwang)
- [Links](links.html) 

